import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { DuckDBInstance } from '@duckdb/node-api'

const API_URL = 'https://db.ygoprodeck.com/api/v7/cardinfo.php?misc=yes'
const SRC = 'data-src/yugioh'
const OUT = 'public/worlds/yugioh'

// YGOPRODeck card types that aren't real playable cards (Token = generated by
// card effects, not a deck card; Skill Card = Duel Links only) — excluded so
// every row in the world is a card a learner could actually be asked about.
const EXCLUDED_TYPES = new Set(['Token', 'Skill Card'])

interface Ygoprodeck {
  data: RawCard[]
}
interface RawCard {
  id: number
  name: string
  type: string
  race: string
  attribute?: string
  atk?: number
  def?: number
  level?: number
  archetype?: string
  card_sets?: { set_name: string; set_code: string; set_rarity: string }[]
  banlist_info?: { ban_tcg?: string; ban_ocg?: string; ban_goat?: string }
}

mkdirSync(SRC, { recursive: true })
mkdirSync(OUT, { recursive: true })

const rawPath = `${SRC}/cardinfo.json`
if (!existsSync(rawPath)) {
  console.log('downloading cardinfo.json…')
  const res = await fetch(API_URL)
  if (!res.ok) throw new Error(`cardinfo.php: HTTP ${res.status}`)
  writeFileSync(rawPath, Buffer.from(await res.arrayBuffer()))
} else {
  console.log(`${rawPath} already cached, skipping fetch`)
}

const raw = JSON.parse(readFileSync(rawPath, 'utf8')) as Ygoprodeck

const cards = raw.data.filter(c => !EXCLUDED_TYPES.has(c.type))

const cardsOut = cards.map(c => ({
  id: c.id,
  name: c.name,
  type: c.type,
  race: c.race,
  attribute: c.attribute ?? null,
  atk: c.atk ?? null,
  def: c.def ?? null,
  level: c.level ?? null,
  archetype: c.archetype ?? null,
}))

const cardSetsOut: { card_id: number; set_name: string; set_code: string; rarity: string }[] = []
for (const c of cards) {
  for (const s of c.card_sets ?? []) {
    cardSetsOut.push({ card_id: c.id, set_name: s.set_name, set_code: s.set_code, rarity: s.set_rarity })
  }
}

// Plan scope: only tcg/ocg formats (ban_goat, when present, is out of scope).
const banlistOut: { card_id: number; format: string; status: string }[] = []
for (const c of cards) {
  if (!c.banlist_info) continue
  if (c.banlist_info.ban_tcg) banlistOut.push({ card_id: c.id, format: 'tcg', status: c.banlist_info.ban_tcg })
  if (c.banlist_info.ban_ocg) banlistOut.push({ card_id: c.id, format: 'ocg', status: c.banlist_info.ban_ocg })
}

const toJsonl = (rows: object[]) => rows.map(r => JSON.stringify(r)).join('\n') + '\n'
writeFileSync(`${SRC}/cards.jsonl`, toJsonl(cardsOut))
writeFileSync(`${SRC}/card_sets.jsonl`, toJsonl(cardSetsOut))
writeFileSync(`${SRC}/banlist.jsonl`, toJsonl(banlistOut))
console.log(`transformed ${cardsOut.length} cards, ${cardSetsOut.length} card_sets, ${banlistOut.length} banlist rows`)

const db = await DuckDBInstance.create()
const conn = await db.connect()

await conn.run(`
CREATE TABLE cards AS
SELECT * FROM read_json('${SRC}/cards.jsonl', format = 'newline_delimited', columns = {
  id: 'BIGINT', name: 'VARCHAR', type: 'VARCHAR', race: 'VARCHAR',
  attribute: 'VARCHAR', atk: 'BIGINT', def: 'BIGINT', level: 'BIGINT', archetype: 'VARCHAR'
})
ORDER BY id
`)

await conn.run(`
CREATE TABLE card_sets AS
SELECT * FROM read_json('${SRC}/card_sets.jsonl', format = 'newline_delimited', columns = {
  card_id: 'BIGINT', set_name: 'VARCHAR', set_code: 'VARCHAR', rarity: 'VARCHAR'
})
ORDER BY card_id, set_code, rarity
`)

await conn.run(`
CREATE TABLE banlist AS
SELECT * FROM read_json('${SRC}/banlist.jsonl', format = 'newline_delimited', columns = {
  card_id: 'BIGINT', format: 'VARCHAR', status: 'VARCHAR'
})
ORDER BY card_id, format
`)

for (const table of ['cards', 'card_sets', 'banlist']) {
  await conn.run(`COPY ${table} TO '${OUT}/${table}.parquet' (FORMAT parquet)`)
  const reader = await conn.runAndReadAll(`SELECT COUNT(*) AS n FROM ${table}`)
  console.log(`wrote ${OUT}/${table}.parquet with ${reader.getRows()[0][0]} rows`)
}

const schema = {
  world: 'yugioh',
  name: 'Yu-Gi-Oh!',
  entity: { table: 'cards', column: 'name', labelColumn: 'type' },
  tables: [
    {
      name: 'cards',
      description: 'One row per Yu-Gi-Oh! trading card (excludes Tokens and Duel Links Skill Cards)',
      columns: [
        { name: 'id', type: 'BIGINT', description: 'Unique card passcode' },
        { name: 'name', type: 'VARCHAR', description: 'Card name, e.g. Dark Magician' },
        { name: 'type', type: 'VARCHAR', description: "Card type, e.g. 'Normal Monster', 'Spell Card', 'Trap Card'" },
        {
          name: 'race',
          type: 'VARCHAR',
          description: "Monster type for monsters (e.g. Spellcaster, Dragon) or subtype for Spell/Trap cards (e.g. Continuous, Quick-Play)",
        },
        { name: 'attribute', type: 'VARCHAR', description: 'Monster attribute, e.g. DARK, LIGHT — NULL for Spell/Trap cards' },
        { name: 'atk', type: 'BIGINT', description: 'Attack points — NULL for Spell/Trap cards' },
        { name: 'def', type: 'BIGINT', description: 'Defense points — NULL for Spell/Trap cards and Link Monsters (which have no DEF)' },
        { name: 'level', type: 'BIGINT', description: 'Level or Rank — NULL for Spell/Trap cards and Link Monsters' },
        { name: 'archetype', type: 'VARCHAR', description: "Card series/archetype, e.g. 'Dark Magician' — NULL if the card belongs to none" },
      ],
    },
    {
      name: 'card_sets',
      description: 'One row per (card, printing) — a card reprinted in multiple sets or rarities has multiple rows',
      columns: [
        { name: 'card_id', type: 'BIGINT', description: 'References cards.id' },
        { name: 'set_name', type: 'VARCHAR', description: 'Name of the set the card was printed in, e.g. Legend of Blue Eyes White Dragon' },
        { name: 'set_code', type: 'VARCHAR', description: 'Print code, e.g. LOB-005' },
        { name: 'rarity', type: 'VARCHAR', description: 'Print rarity, e.g. Ultra Rare' },
      ],
    },
    {
      name: 'banlist',
      description: 'Restricted-card list entries — only cards that are Forbidden, Limited, or Semi-Limited in a format appear here',
      columns: [
        { name: 'card_id', type: 'BIGINT', description: 'References cards.id' },
        { name: 'format', type: 'VARCHAR', description: "Competitive format: 'tcg' or 'ocg'" },
        { name: 'status', type: 'VARCHAR', description: "Restriction status: 'Forbidden' (0 copies), 'Limited' (1 copy), or 'Semi-Limited' (2 copies)" },
      ],
    },
  ],
}
writeFileSync(`${OUT}/schema.json`, JSON.stringify(schema, null, 2))
console.log(`wrote ${OUT}/schema.json`)

// --- Post-build sanity checks (standalone: harness won't load this world until Phase C) ---
console.log('\n--- sanity checks ---')

const dm = await conn.runAndReadAll(`SELECT race FROM cards WHERE name = 'Dark Magician'`)
const dmRows = dm.getRows()
console.log(`Dark Magician exists, race = ${dmRows[0]?.[0] ?? 'MISSING'}`)
if (dmRows.length === 0 || dmRows[0][0] !== 'Spellcaster') {
  throw new Error('sanity check failed: Dark Magician missing or race != Spellcaster')
}

const spellNullAtk = await conn.runAndReadAll(
  `SELECT name FROM cards WHERE type = 'Spell Card' AND atk IS NULL LIMIT 1`,
)
console.log(`Spell Card with NULL atk: ${spellNullAtk.getRows()[0]?.[0] ?? 'NONE FOUND'}`)
if (spellNullAtk.getRows().length === 0) throw new Error('sanity check failed: no Spell Card with NULL atk found')

const bannedTcg = await conn.runAndReadAll(
  `SELECT COUNT(*) FROM banlist WHERE format = 'tcg' AND status = 'Forbidden'`,
)
console.log(`banlist rows with format=tcg, status=Forbidden: ${bannedTcg.getRows()[0][0]}`)
if (Number(bannedTcg.getRows()[0][0]) === 0) throw new Error('sanity check failed: no Forbidden tcg banlist rows found')

for (const table of ['cards', 'card_sets', 'banlist']) {
  const r = await conn.runAndReadAll(`SELECT COUNT(*) FROM ${table}`)
  console.log(`${table}: ${r.getRows()[0][0]} rows`)
}

console.log('\nall sanity checks passed')
